// Crest Ocean System

// This file is subject to the MIT License as seen in the root of this folder structure (LICENSE)

#pragma kernel SplatWaveParticles

#include "../OceanLODData.hlsl"

RWTexture2DArray<float4> _LD_TexArray_Target;

[numthreads(THREAD_GROUP_SIZE_X,THREAD_GROUP_SIZE_Y,1)]
void SplatWaveParticles(uint3 id : SV_DispatchThreadID)
{
	float3 displacement = float3(0, sin(id.x + id.y), 0);
	_LD_TexArray_Target[uint3(id.xy, _LD_SliceIndex)] = float4(displacement, 0.0);
}
